### ISSUE TITLE
thanks,  now its getting better,  but without the comfy-manager   Iguess i have to import the missing nodes  manually     .. but anyway  thanks for your effort !!

### ISSUE THREAD

**Issue by eflin1** [YanWenKun/Comfy3D-WinPortable#1]

**Comment by YanWenKun** [comment]
@eflin1 Here's a new release that came with ComfyUI-Manager:
https://github.com/YanWenKun/Comfy3D-WinPortable/releases/tag/r4-pt25

It's a pre-release though. The next release will include ComfyUI-Manager as well.
