### ISSUE TITLE
Trellis

### ISSUE THREAD

**Issue by Abocg** [YanWenKun/Comfy3D-WinPortable#2]
Thank you so much for all the incredible work you are doing. But any chance to install this node to comfy https://github.com/if-ai/ComfyUI-IF_Trellis  Trellis  is the best AI model for 3D model and am having hard time installing it snice am 3D artis not a programmer.. many thanks in advance

**Comment by YanWenKun** [comment]
I see 3D-Pack is [preparing](https://github.com/MrForExample/Comfy3D_Pre_Builds/commit/606a5cf09aef1ecaf0092f6b645ac46bc2772d86) for Trellis. I guess it won't be long before we see the new workflow.

**Comment by YanWenKun** [comment]
The TRELLIS Special is out:
https://github.com/YanWenKun/Comfy3D-WinPortable/releases/tag/r4-pt25
