### ISSUE TITLE
Comfy3D_WinPortable.7z.002 Not Opening in 7-zip

### ISSUE THREAD

**Issue by Ossenbrugge** [YanWenKun/Comfy3D-WinPortable#3]
Hi, 

I was able to get the first file to open and extract. However when I tried to extract the second one 7-zip said "Error: is not an archive." 

Do I even need the file? I tried the first time install.bat and it seems to be working fine. Thanks!

**Comment by YanWenKun** [comment]
You did right! When you open and extra the `.7z.001` file, it automatically opens follow `.002` `.003` `.004` .... as well.

**Comment by Ossenbrugge** [comment]
Thanks! Much appreciated, so far everything is working, although I've had some odd renders from CharacterGen_to_Unique3D (the AI tried to make the mesh but it looked more like a bad 3D print than a model).

Any support for Trellis, upcoming? Also, thanks for this project! It is very helpful!

**Comment by YanWenKun** [comment]
Glad you like it!

I'm debugging the TRELLIS build these days. It has some compatibility issues for now. I'll let you know when it's ready! 😉

**Comment by YanWenKun** [comment]
The TRELLIS Special is out:
https://github.com/YanWenKun/Comfy3D-WinPortable/releases/tag/r4-pt25

**Comment by coddz** [comment]
Great work, TRELLIS Special! 

webui like hf space and comfyui, all in one.
